name: BREDeployer
on: push
     

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: WhoAmI (Service Principal)
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
          environment-url: ${{ secrets.DEPLOYMENT_APPSOURCEURL }}
          app-id:        ${{ secrets.DEPLOYMENT_APPID }}
          client-secret: ${{ secrets.DEPLOYMENT_APPSECRET }}
          tenant-id:     ${{ secrets.DEPLOYMENT_TENANTID }}

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
          environment-url: ${{ secrets.DEPLOYMENT_APPSOURCEURL }}
          app-id: ${{ secrets.DEPLOYMENT_APPID }}
          client-secret: ${{ secrets.DEPLOYMENT_APPSECRET }}
          tenant-id:     ${{ secrets.DEPLOYMENT_TENANTID }}
          solution-name: 'BasicRealEstate'
          solution-output-file: 'BasicRealEstate.zip'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
          solution-file: 'BasicRealEstate.zip'
          solution-folder: 'solutions/BasicRealEstate'
          solution-type: 'Unmanaged'
          overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
          environment-url: ${{ secrets.DEPLOYMENT_APPSOURCEURL }}
          app-id: ${{ secrets.DEPLOYMENT_APPID }}
          client-secret: ${{ secrets.DEPLOYMENT_APPSECRET }}
          tenant-id:     ${{ secrets.DEPLOYMENT_TENANTID }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
          solution-folder: 'solutions/BasicRealEstate'
          solution-target-folder: 'src/solutions/BasicRealEstate'
          repo-token: ${{ secrets.DEPLOYMENT_BRE_TOKEN }}
